<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-10T00:17:26 EEST" name="Default suite" finished-at="2025-04-10T00:19:04 EEST" duration-ms="98247">
    <groups>
    </groups>
    <test started-at="2025-04-10T00:17:26 EEST" name="Default test" finished-at="2025-04-10T00:19:04 EEST" duration-ms="98247">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.LoginTest@692f203f]" started-at="2025-04-10T00:17:26 EEST" name="setUp" finished-at="2025-04-10T00:17:29 EEST" duration-ms="3036" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@692f203f]" started-at="2025-04-10T00:17:31 EEST" name="testLogin" data-provider="loginData" finished-at="2025-04-10T00:17:52 EEST" duration-ms="21073" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[testuserexample.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@692f203f]" started-at="2025-04-10T00:17:52 EEST" name="testLogin" data-provider="loginData" finished-at="2025-04-10T00:18:28 EEST" duration-ms="36287" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[validuser@example.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[wrongpassword123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The displayed message does not match the expected result. expected [Email/Password you entered is not correct. Please try again.] but found [You May Also Like]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The displayed message does not match the expected result. expected [Email/Password you entered is not correct. Please try again.] but found [You May Also Like]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at tests.LoginTest.testLogin(LoginTest.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@692f203f]" started-at="2025-04-10T00:18:28 EEST" name="testLogin" data-provider="loginData" finished-at="2025-04-10T00:19:04 EEST" duration-ms="35601" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[ebakhalil7@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456789Eba@@]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginTest@692f203f]" started-at="2025-04-10T00:19:04 EEST" name="tearDown" finished-at="2025-04-10T00:19:04 EEST" duration-ms="926" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
